### ISSUE TITLE
Error with translator

### ISSUE THREAD

**Issue by Arkyos** [fabiopaiva/ZfcUserCrud#3]
Hi,

I've installed your module but I have an error when I go on the new, edit and remove pages.

Error : Zend\ServiceManager\ServiceManager::get was unable to fetch or create an instance for translator

**Comment by fabiopaiva** [comment]
Hi @Arkyos, check you have translator in your service and intl extension in PHP
Can you post the trace error?

**Comment by Arkyos** [comment]
This is the trace error :

#0 C:\wamp\www\easytransatmanager\vendor\fabiopaiva\zfc-user-crud\src\ZfcUserCrud\Controller\RoleController.php(54): Zend\ServiceManager\ServiceManager->get('translator')
#1 C:\wamp\www\easytransatmanager\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractActionController.php(83): ZfcUserCrud\Controller\RoleController->newAction()
#2 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#3 C:\wamp\www\easytransatmanager\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#4 C:\wamp\www\easytransatmanager\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#5 C:\wamp\www\easytransatmanager\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractController.php(116): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#6 C:\wamp\www\easytransatmanager\vendor\zendframework\zendframework\library\Zend\Mvc\DispatchListener.php(113): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#7 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#8 C:\wamp\www\easytransatmanager\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#9 C:\wamp\www\easytransatmanager\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 C:\wamp\www\easytransatmanager\vendor\zendframework\zendframework\library\Zend\Mvc\Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 C:\wamp\www\easytransatmanager\public\index.php(19): Zend\Mvc\Application->run()
#12 {main}

**Comment by fabiopaiva** [comment]
Test this resource 

http://framework.zend.com/manual/current/en/modules/zend.i18n.view.helpers.html#translate-helper

**Comment by Arkyos** [comment]
Why in the module.config there is zfcusercrud_options in the service manager but not translator ? I think the problem is here.

**Comment by fabiopaiva** [comment]
The translator normally is present in ZendSkeletonApplication

https://github.com/zendframework/ZendSkeletonApplication/blob/master/module/Application/config/module.config.php#L61

**Comment by Arkyos** [comment]
I have a new error : Class '' does not exist

Trace error : 

#0 C:\wamp\www\easytransatmanager\vendor\doctrine\common\lib\Doctrine\Common\Persistence\Mapping\RuntimeReflectionService.php(43): Doctrine\Common\Persistence\Mapping\MappingException::nonExistingClass(NULL)
#1 C:\wamp\www\easytransatmanager\vendor\doctrine\common\lib\Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory.php(267): Doctrine\Common\Persistence\Mapping\RuntimeReflectionService->getParentClasses(NULL)
#2 C:\wamp\www\easytransatmanager\vendor\doctrine\common\lib\Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory.php(297): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getParentClasses(NULL)
#3 C:\wamp\www\easytransatmanager\vendor\doctrine\common\lib\Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory.php(211): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata(NULL)
#4 C:\wamp\www\easytransatmanager\vendor\doctrine\orm\lib\Doctrine\ORM\EntityManager.php(265): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor(NULL)
#5 C:\wamp\www\easytransatmanager\vendor\doctrine\doctrine-module\src\DoctrineModule\Stdlib\Hydrator\DoctrineObject.php(76): Doctrine\ORM\EntityManager->getClassMetadata(NULL)
#6 C:\wamp\www\easytransatmanager\vendor\fabiopaiva\zfc-user-crud\src\ZfcUserCrud\Controller\RoleController.php(118): DoctrineModule\Stdlib\Hydrator\DoctrineObject->__construct(Object(Doctrine\ORM\EntityManager))
#7 C:\wamp\www\easytransatmanager\vendor\fabiopaiva\zfc-user-crud\src\ZfcUserCrud\Controller\RoleController.php(55): ZfcUserCrud\Controller\RoleController->getForm()
#8 C:\wamp\www\easytransatmanager\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractActionController.php(83): ZfcUserCrud\Controller\RoleController->newAction()
#9 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#10 C:\wamp\www\easytransatmanager\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#11 C:\wamp\www\easytransatmanager\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 C:\wamp\www\easytransatmanager\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractController.php(116): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#13 C:\wamp\www\easytransatmanager\vendor\zendframework\zendframework\library\Zend\Mvc\DispatchListener.php(113): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#14 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#15 C:\wamp\www\easytransatmanager\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#16 C:\wamp\www\easytransatmanager\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#17 C:\wamp\www\easytransatmanager\vendor\zendframework\zendframework\library\Zend\Mvc\Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#18 C:\wamp\www\easytransatmanager\public\index.php(19): Zend\Mvc\Application->run()
#19 {main}

**Comment by fabiopaiva** [comment]
It's look like Doctrine problem. Check if you have configured ZfcUserDoctrineORM correctly
https://github.com/ZF-Commons/ZfcUserDoctrineORM

**Comment by Arkyos** [comment]
Hi,

in the CrudController and RoleController, the problem is here : new DoctrineHydrator($this->getOM()).
The constructor of DoctrineObject needs 2 paramaters (ObjectManager $objectManager, $targetClass, $byValue = true) but you give only one.

**Comment by fabiopaiva** [comment]
Don't have targetClass

https://github.com/doctrine/DoctrineModule/blob/master/src/DoctrineModule/Stdlib/Hydrator/DoctrineObject.php#L69
